### ISSUE TITLE
datatables search items not highlighted when data loaded by ajax.reload()

### ISSUE THREAD

**Issue by dave-k** [julmot/datatables.mark.js#3]
When datatables data is loaded with table.ajax.reload(), 
search for items are not highlighted.
See fiddles below.

1. http://live.datatables.net/lovukesu/3/edit
Example with no highlight - table.ajax.reload(null, false);:
    "ajax": {
          "contentType": 'application/json; charset=utf-8',
          "dataSrc": "",
          "url": ""
    },
    var URL = "//jsonplaceholder.typicode.com/users";
    table.ajax.url(URL);
    table.ajax.reload(null, false);

2. http://live.datatables.net/lovukesu/1/edit
Example with highlight:
    "ajax": {
          "contentType": 'application/json; charset=utf-8',
          "dataSrc": "",
          "url": "//jsonplaceholder.typicode.com/users"
    },

jquery v1.11.3
jquery.mark  v7.0.0
datatables.mark v 1.0.1
datatables v1.10.12

**Comment by julmot** [comment]
Hi @dave-k ,

Thanks for submitting!

This seems to be an issue with how you initialize DataTables. Normally, when you've initialized a DataTables instance correctly, an event `init.dt.dth` will be fired through the document. This is necessary for datatables.mark.js in order to work. As this event isn't fired in your first example, it won't highlight terms.

To fix this issue, you might re-read the documentation of DataTables. This seems to work: http://live.datatables.net/lovukesu/4/edit

**Comment by DataTables** [comment]
The initialisation mostly looks okay - although a little unusual in two places:

* No URL given in the initialisation for an Ajax data sourced table (presumably that's just for this test case)
* If you call `ajax.reload()` immediately after the table's initialisation (but _before_ the data has been loaded - like in the given example) Mark.js isn't highlight the row. I'm not sure if that is because an event isn't triggered by DataTables or something else. However, I would very much suggest that with an async table like this, the `init.dt` event is used like @julmot suggests, or use `initComplete`: http://live.datatables.net/lovukesu/5/edit .

In that example I've also added a button so you can trigger reloading of the table's data at any time and that appears to work okay.

There is a bug somewhere here, but it is being triggered by a use case that I would recommend avoiding away.

**Comment by julmot** [comment]
@DataTables 

>  I'm not sure if that is because an event isn't triggered by DataTables or something else

The event `$(document).on("init.dt.dth", fn);` isn't fired in his first example.

> There is a bug somewhere here

From my point of view this bug is on the DataTables side – as I expect the event to get fired. Can you confirm this?

**Comment by DataTables** [comment]
Its not being triggered in the first example because an `ajax.reload()` is being triggered before the table's data has been loaded. That means that the first Ajax request DataTables sends out is being cancelled and "lost". That one happens to have the init complete callback on it, which thus never happens.

So yes, this is a bug in DataTables, which I've now taken a note of. However, as noted above, I would very much recommend not uses DataTables' API in this way. Wait for the initialisation to complete before then doing something with it.
